## Pandas - 04

## GroupBy Object

In [3]:
import numpy as np
import pandas as pd

In [4]:
movies= pd.read_csv("imdb-top-1000.csv")
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [ ]:
# GroupBy ---> it makeGroups Based on Categories.s the 
# it applies to categorical columns.

In [5]:
# .groupby("column_name")
genres= movies.groupby("Genre") # pandas makes the Groups but it will not display it
type(genres) # its datatype is (Pandas DataFrame GroupBy Object)

pandas.api.typing.DataFrameGroupBy

## Applying builtin aggregation functions on groupby objects

In [18]:

# Aggregation Functions
# min/max/count/sum/var/std/mean/median/mode etc....

# For those functions that only apply on Numerical Columns should use parameter : numeric_only = True


genres.sum(numeric_only=True).head(5) # ---> each category has its own table and when we apply sum on genres each category performs its individual sum 
print(type(genres.sum()))  # its type is dataframe
genres.min(numeric_only= True).head(5)

<class 'pandas.DataFrame'>

           Runtime  IMDB_Rating  No_of_Votes     Gross  Metascore
Genre
Action          45          7.6        25312    3296.0       33.0
Adventure       88          7.6        29999   61001.0       41.0
Animation       71          7.6        25229  128985.0       61.0
Biography       93          7.6        27254   21877.0       48.0
Comedy          68          7.6        26337    1305.0       45.0

In [19]:
genres.max(numeric_only=True).head(3) 
genres.mean(numeric_only=True).head() # mean of numerical columns for each category

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000

## Questions

In [ ]:
# 1: find the top three genres by total earning
# 1st method ---> first sum then fetch the column "Gross"
movies.groupby("Genre").sum()["Gross"].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [ ]:
# 2nd method: first fetch the column "Gross" then apply sum on only it. ( This is more  Convinient/reliable and most method to do this.)
movies.groupby("Genre")["Gross"].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [42]:
# 2: Find the genre with highest avg IMDB Rating.
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending= False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [ ]:
# 3: find director with most popularity
movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending= False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [ ]:
# 4: find number of movies done by each actor.
# My logic
movies.groupby("Star1")["Series_Title"].count().sort_values(ascending=False)

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [17]:
# easy method
movies["Star1"].value_counts()

Star1
Tom Hanks            12
Robert De Niro       11
Al Pacino            10
Clint Eastwood       10
Leonardo DiCaprio     9
                     ..
Phil Harris           1
David Hemmings        1
John Lennon           1
Tallulah Bankhead     1
Robert Donat          1
Name: count, Length: 660, dtype: int64

## Groupby Attributes & Methods

In [ ]:
# find total number of groups --> len
len(movies.groupby("Genre")) # gives how many groups are made of genres means how many different types of genres are there

14

In [19]:
# using nunique to get:
movies["Genre"].nunique()

14

In [ ]:
# how many items in each group ---> size() --> ( gives result in series)
movies.groupby("Genre").size() # ---> give the no. of movies in each Genre(Category/Group) ---> prefer this

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [ ]:
# same result also by:
movies["Genre"].value_counts() # it is sorted

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [3]:
# first() ---> fetch the first movie of each group in a dataframe
genres= movies.groupby("Genre") # ---> genres is a groupby object
genres.first() # ----> it gives the first movie of each Genre(Group).

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [ ]:
# last() ---> fetch the last movie of each group in a dataframe
genres.last() # ----> it gives the last movie of each Genre(Group).

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [ ]:
# nth() ---> give the nth(index) movie of each group in a dataframe.
genres.nth(6) # ---> give the 6th index (7th movie) of each Genre(Group)
# Note: Many groups are not there because many groups haven't 6th index movies they have movies lower than that index.

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [ ]:
# get_group() --->fetching a particular group.
genres.get_group("Adventure") # ---> faster than boolean masking and filtering

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
110,Das Boot,1981,149,Adventure,8.3,Wolfgang Petersen,Jürgen Prochnow,231855,11487676.0,86.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
...,...,...,...,...,...,...,...,...,...,...
957,Fear and Loathing in Las Vegas,1998,118,Adventure,7.6,Terry Gilliam,Johnny Depp,259753,10680275.0,41.0
964,Dead Man,1995,121,Adventure,7.6,Jim Jarmusch,Johnny Depp,90442,1037847.0,62.0
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.0
984,The Muppet Movie,1979,95,Adventure,7.6,James Frawley,Jim Henson,32802,76657000.0,74.0
991,Kelly's Heroes,1970,144,Adventure,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0

In [ ]:
# by using filtering:
movies[movies["Genre"] =="Adventure"]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
110,Das Boot,1981,149,Adventure,8.3,Wolfgang Petersen,Jürgen Prochnow,231855,11487676.0,86.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
...,...,...,...,...,...,...,...,...,...,...
957,Fear and Loathing in Las Vegas,1998,118,Adventure,7.6,Terry Gilliam,Johnny Depp,259753,10680275.0,41.0
964,Dead Man,1995,121,Adventure,7.6,Jim Jarmusch,Johnny Depp,90442,1037847.0,62.0
966,Apollo 13,PG,140,Adventure,7.6,Ron Howard,Tom Hanks,269197,173837933.0,77.0
984,The Muppet Movie,1979,95,Adventure,7.6,James Frawley,Jim Henson,32802,76657000.0,74.0
991,Kelly's Heroes,1970,144,Adventure,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0

In [ ]:
# groups --->attribute
# gives a dictionary in which keys are groups and values are lists in which the group items indices are stored.
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [ ]:
# describe() --> gives the high mathematical information of all groups in a dataframe (same as in series and dataframe)
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [ ]:
# sample() # ---> randomly give item (movies) from each group (default 1)
# replace=True parameter ---> means if we select 2 and a group has only 1 it repeats the 1 and complete the 2
genres.sample(2,replace = True) # fetch 2 movies from each group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
839,Star Trek II: The Wrath of Khan,1982,113,Action,7.7,Nicholas Meyer,William Shatner,112704,78912963.0,67.0
623,Avatar,2009,162,Action,7.8,James Cameron,Sam Worthington,1118998,760507625.0,83.0
402,Dances with Wolves,1990,181,Adventure,8.0,Kevin Costner,Kevin Costner,240266,184208848.0,72.0
137,Queen,2013,146,Adventure,8.2,Vikas Bahl,Kangana Ranaut,60701,1429534.0,NaN
744,The Lego Movie,2014,100,Animation,7.7,Christopher Miller,Phil Lord,323982,257760692.0,83.0
146,Up,2009,96,Animation,8.2,Pete Docter,Bob Peterson,935507,293004164.0,88.0
429,The Sound of Music,1965,172,Biography,8.0,Robert Wise,Julie Andrews,205425,163214286.0,63.0
359,Dallas Buyers Club,2013,117,Biography,8.0,Jean-Marc Vallée,Matthew McConaughey,441614,27298285.0,80.0
687,The King of Comedy,1982,109,Comedy,7.8,Martin Scorsese,Robert De Niro,88511,2500000.0,73.0
374,Kal Ho Naa Ho,2003,186,Comedy,8.0,Nikkhil Advani,Preity Zinta,63460,1787378.0,54.0
895,Leviafan,2014,140,Crime,7.6,Andrey Zvyagintsev,Aleksey Serebryakov,49397,1092800.0,92.0
305,On the Waterfront,1954,108,Crime,8.1,Elia Kazan,Marlon Brando,142107,9600000.0,91.0
572,Forushande,2016,124,Drama,7.8,Asghar Farhadi,Shahab Hosseini,51240,2402067.0,85.0
303,Kumonosu-jô,1957,110,Drama,8.1,Akira Kurosawa,Toshirô Mifune,46678,612604239.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [37]:
# nunique ---> gives the no. of unique values for each column in the dataframe for groupby object
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [38]:
genres.sum(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [ ]:
# agg() method ---> passing dict --> apply different aggregate functions on differnt columns by passing a dictionary.
# {"column_name":"aggregate_method_name"}

# condition 01: applying different but one aggregate function to each column.
genres.agg(
    {
        "Runtime":"mean",
        "IMDB_Rating":"mean",
        "No_of_Votes": "sum",
        "Gross":"sum",
        "Metascore":"mean"
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10  73.419580
Adventure  134.111111     7.937500     22576163  9.496922e+09  78.437500
Animation   99.585366     7.930488     21978630  1.463147e+10  81.093333
Biography  136.022727     7.938636     24006844  8.276358e+09  76.240506
Comedy     112.129032     7.901290     27620327  1.566387e+10  78.720000
Crime      126.392523     8.016822     33533615  8.452632e+09  77.080460
Drama      124.737024     7.957439     61367304  3.540997e+10  79.701245
Family     107.500000     7.800000       551221  4.391106e+08  79.000000
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08  95.666667
Horror     102.090909     7.909091      3742556  1.034649e+09  80.000000
Mystery    119.083333     7.975000      4203004  1.256417e+09  79.125000
Thriller   108.000000     7.800000        27733  1.755074e+07  81.000000
Western    148.250000     8.350000      1289665  5.822151e+07  78.250000

In [ ]:
# Condition 02: applying multiple functions to all  columns
genres.agg(
    {
    "Runtime":["sum","min","max","mean"],
        "IMDB_Rating":["sum","min","max","mean"],
        "No_of_Votes": ["sum","min","max","mean"],
        "Gross":["sum","min","max","mean"],
        "Metascore":["sum","min","max","mean"]
}
)
# by using this we can get all lot of information about the data.

          Runtime                       IMDB_Rating                      \
              sum  min  max        mean         sum  min  max      mean
Genre
Action      22196   45  321  129.046512      1367.3  7.6  9.0  7.949419
Adventure    9656   88  228  134.111111       571.5  7.6  8.6  7.937500
Animation    8166   71  137   99.585366       650.3  7.6  8.6  7.930488
Biography   11970   93  209  136.022727       698.6  7.6  8.9  7.938636
Comedy      17380   68  188  112.129032      1224.7  7.6  8.6  7.901290
Crime       13524   80  229  126.392523       857.8  7.6  9.2  8.016822
Drama       36049   64  242  124.737024      2299.7  7.6  9.3  7.957439
Family        215  100  115  107.500000        15.6  7.8  7.8  7.800000
Fantasy       170   76   94   85.000000        16.0  7.9  8.1  8.000000
Film-Noir     312  100  108  104.000000        23.9  7.8  8.1  7.966667
Horror       1123   71  122  102.090909        87.0  7.6  8.5  7.909091
Mystery      1429   96  138  119.083333        95.7  7.6  8.4  7.975000
Thriller      108  108  108  108.000000         7.8  7.8  7.8  7.800000
Western       593  132  165  148.250000        33.4  7.8  8.8  8.350000

          No_of_Votes                                         Gross  \
                  sum     min      max           mean           sum
Genre
Action       72282412   25312  2303232  420246.581395  3.263226e+10
Adventure    22576163   29999  1512360  313557.819444  9.496922e+09
Animation    21978630   25229   999790  268032.073171  1.463147e+10
Biography    24006844   27254  1213505  272805.045455  8.276358e+09
Comedy       27620327   26337   939631  178195.658065  1.566387e+10
Crime        33533615   27712  1826188  313398.271028  8.452632e+09
Drama        61367304   25088  2343110  212343.612457  3.540997e+10
Family         551221  178731   372490  275610.500000  4.391106e+08
Fantasy        146222   57428    88794   73111.000000  7.827267e+08
Film-Noir      367215   59556   158731  122405.000000  1.259105e+08
Horror        3742556   27007   787806  340232.363636  1.034649e+09
Mystery       4203004   33982  1129894  350250.333333  1.256417e+09
Thriller        27733   27733    27733   27733.000000  1.755074e+07
Western       1289665   65659   688390  322416.250000  5.822151e+07

                                                  Metascore               \
                   min          max          mean       sum   min    max
Genre
Action          3296.0  936662225.0  1.897224e+08   10499.0  33.0   98.0
Adventure      61001.0  874211619.0  1.319017e+08    5020.0  41.0  100.0
Animation     128985.0  873839108.0  1.784326e+08    6082.0  61.0   96.0
Biography      21877.0  753585104.0  9.404952e+07    6023.0  48.0   97.0
Comedy          1305.0  886752933.0  1.010572e+08    9840.0  45.0   99.0
Crime           6013.0  790482117.0  7.899656e+07    6706.0  47.0  100.0
Drama           3600.0  924558264.0  1.225259e+08   19208.0  28.0  100.0
Family       4000000.0  435110554.0  2.195553e+08     158.0  67.0   91.0
Fantasy    337574718.0  445151978.0  3.913633e+08       0.0   NaN    NaN
Film-Noir     449191.0  123353292.0  4.197018e+07     287.0  94.0   97.0
Horror         89029.0  298791505.0  9.405902e+07     880.0  46.0   97.0
Mystery      1035953.0  474203697.0  1.047014e+08     633.0  52.0  100.0
Thriller    17550741.0   17550741.0  1.755074e+07      81.0  81.0   81.0
Western      5321508.0   31800000.0  1.455538e+07     313.0  69.0   90.0


                mean
Genre
Action     73.419580
Adventure  78.437500
Animation  81.093333
Biography  76.240506
Comedy     78.720000
Crime      77.080460
Drama      79.701245
Family     79.000000
Fantasy          NaN
Film-Noir  95.666667
Horror     80.000000
Mystery    79.125000
Thriller   81.000000
Western    78.250000

In [ ]:
# Looping on groups
# "group" is the name of the group in a str datatype and "data" is the dataframe of each group. i.e. action movies has its own dataframe and adventure has its own by looping it we can get all groups --> dataframe in data variable

for group,data in genres: 
    print(group) # group name
    print(data) # group dataframe

Action
                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
Adventure
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
Animation
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
Biography
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
Comedy
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
Crime
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
Drama
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
Family
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
Fantasy
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
Film-Noir
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
Horror
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
Mystery
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
Thriller
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore

In [7]:
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [7]:
# Question: find the highest rated movie of each genre.
df= pd.DataFrame(columns=movies.columns) # creating empty dataframe that has column same as in movies dataframe


for group,data in genres:
    print(data[data["IMDB_Rating"] == data["IMDB_Rating"].max()])
    
    
    

# now append function is not working thats why i cannot store the output in the empty dataframe i will check it later.
# but the question is solved

      Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
2  The Dark Knight          2008      152  Action          9.0

            Director           Star1  No_of_Votes        Gross  Metascore
2  Christopher Nolan  Christian Bale      2303232  534858444.0       84.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
21  Interstellar          2014      169  Adventure          8.6

             Director                Star1  No_of_Votes        Gross  \
21  Christopher Nolan  Matthew McConaughey      1512360  188020017.0

    Metascore
21       74.0
                     Series_Title Released_Year  Runtime      Genre  \
23  Sen to Chihiro no kamikakushi          2001      125  Animation

    IMDB_Rating        Director          Star1  No_of_Votes       Gross  \
23          8.6  Hayao Miyazaki  Daveigh Chase       651376  10055859.0

    Metascore
23       96.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7  Schindler's List          1993      195  Biography          8.9

           Director        Star1  No_of_Votes       Gross  Metascore
7  Steven Spielberg  Liam Neeson      1213505  96898818.0       94.0
       Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
19     Gisaengchung          2019      132  Comedy          8.6
26  La vita è bella          1997      116  Comedy          8.6

           Director            Star1  No_of_Votes       Gross  Metascore
19     Bong Joon Ho     Kang-ho Song       552778  53367844.0       96.0
26  Roberto Benigni  Roberto Benigni       623629  57598247.0       59.0
    Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1  The Godfather          1972      175  Crime          9.2

               Director          Star1  No_of_Votes        Gross  Metascore
1  Francis Ford Coppola  Marlon Brando      1620367  134966411.0      100.0
               Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
0  The Shawshank Redemption          1994      142  Drama          9.3

         Director        Star1  No_of_Votes       Gross  Metascore
0  Frank Darabont  Tim Robbins      2343110  28341469.0       80.0
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0

     Metascore
321        NaN
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating    Director  \
309  The Third Man          1949      104  Film-Noir          8.1  Carol Reed

            Star1  No_of_Votes     Gross  Metascore
309  Orson Welles       158731  449191.0       97.0
   Series_Title Released_Year  Runtime   Genre  IMDB_Rating          Director  \
49       Psycho          1960      109  Horror          8.5  Alfred Hitchcock

              Star1  No_of_Votes       Gross  Metascore
49  Anthony Perkins       604211  32000000.0       97.0
   Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69      Memento          2000      113  Mystery          8.4
81  Rear Window          1954      112  Mystery          8.4

             Director          Star1  No_of_Votes       Gross  Metascore
69  Christopher Nolan     Guy Pearce      1125712  25544867.0       80.0
81   Alfred Hitchcock  James Stewart       444074  36764313.0      100.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0
                       Series_Title Released_Year  Runtime    Genre  \
12  Il buono, il brutto, il cattivo          1966      161  Western

    IMDB_Rating      Director           Star1  No_of_Votes      Gross  \
12          8.8  Sergio Leone  Clint Eastwood       688390  6100000.0

    Metascore
12       90.0

## Split Apply Combine Strategy

In [ ]:
# split ---> split the groups using groupy
#apply ---> apply any logic to all the groups and then #combine

In [8]:
# apply() --> can be used to apply any function: builtin or custom on groups.
movies.groupby("Genre")["No_of_Votes"].apply(max)

Genre
Action       2303232
Adventure    1512360
Animation     999790
Biography    1213505
Comedy        939631
Crime        1826188
Drama        2343110
Family        372490
Fantasy        88794
Film-Noir     158731
Horror        787806
Mystery      1129894
Thriller       27733
Western       688390
Name: No_of_Votes, dtype: int64

In [ ]:
# find number of movies starting with "a" for each group

genres # --> spliting the dataframe into groups by groupBy/
def foo(group): # ----> applying custom logic to every group
    return group["Series_Title"].str.startswith("A").sum()  # type of group is dataframe
    


genres.apply(foo) # --> then again combine
# This is Split Apply Combine Strategy.

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [11]:
# 2: find ranking of each movie in the group according to the IMDB Score

def rank_movie(group):
    group["Genre_Rank"] = group["IMDB_Rating"].rank(ascending = False)
    return group

genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Genre_Rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [ ]:
# 3: find normalized rating (IMDB) for each movie group wise.

def norm(group):
    group["Norm_rating"] =(group["IMDB_Rating"] - group["IMDB_Rating"].min())/(group["IMDB_Rating"].max() -group["IMDB_Rating"].min())
    group["Norm_rating"] = np.round(group["Norm_rating"],2)
    return group # this will return the all groups dataframe not the original one

In [19]:
genres.apply(norm)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Norm_rating
Genre
Action   2        2303232  534858444.0       84.0         1.00
         5        1642758  377845905.0       94.0         0.93
         8        2067042  292576195.0       74.0         0.86
         10       1661481  315544750.0       92.0         0.86
         13       1485555  342551365.0       87.0         0.79
...                   ...          ...        ...          ...
Thriller 700        27733   17550741.0       81.0          NaN
Western  12        688390    6100000.0       90.0         1.00
         48        302844    5321508.0       80.0         0.70
         115       232772   15000000.0       74.0         0.50
         691        65659   31800000.0       69.0         0.00

[1000 rows x 10 columns]

In [ ]:
# group by on multiple cols
duo= movies.groupby(["Director","Star1"]) # passing cols in a list

# size
duo.size()


# get_group # ---> pass in tuple
duo.get_group(("Aamir Khan","Amole Gupte")) # fetching the group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [20]:
# 1: find the most earning actor/Director combo
duo = movies.groupby(["Director","Star1"])
duo["Gross"].sum().sort_values(ascending= False).head(1) # datatype is:  multiindex groupby series

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [ ]:
# 2: find the best (in terms of Metascore (avg)) actor/genre combo
movies.groupby(["Star1","Genre"])["Metascore"].mean().reset_index().sort_values("Metascore",ascending=False)

                Star1      Genre  Metascore
606     Peter O'Toole  Adventure      100.0
590      Orson Welles      Drama      100.0
77        Bertil Guve      Drama      100.0
230    Ellar Coltrane      Drama      100.0
329   Humphrey Bogart      Drama      100.0
..                ...        ...        ...
807    William Holden      Drama        NaN
812           Won Bin     Action        NaN
815              Yash     Action        NaN
826    Çetin Tekindor      Drama        NaN
828  Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

In [34]:
# agg() on multicols groups
duo[["No_of_Votes","Gross","Runtime","Metascore"]].agg(["min","max","mean"])

                               No_of_Votes                          Gross  \
                                       min     max      mean          min
Star1                Genre
Aamir Khan           Action          49300  156479  102889.5   12391761.0
                     Adventure      105036  105036  105036.0      70147.0
                     Comedy          66803  344445  171561.5     300000.0
Aaron Taylor-Johnson Action         524081  524081  524081.0   48071303.0
Abhay Deol           Drama           28749   28749   28749.0      10950.0
...                                    ...     ...       ...          ...
Zbigniew Zamachowski Comedy          64390   64390   64390.0    1464625.0
Zooey Deschanel      Comedy         472242  472242  472242.0   32391374.0
Çetin Tekindor       Drama           78925   78925   78925.0  461855363.0
Éric Toledano        Biography      760360  760360  760360.0   13182281.0
Ömer Faruk Sorak     Comedy          33592   33592   33592.0  200178699.0

                                                          Runtime       \
                                        max          mean     min  max
Star1                Genre
Aamir Khan           Action     213351844.0  1.128718e+08     160  161
                     Adventure      70147.0  7.014700e+04     224  224
                     Comedy      10616104.0  4.911586e+06     153  183
Aaron Taylor-Johnson Action      48071303.0  4.807130e+07     117  117
Abhay Deol           Drama          10950.0  1.095000e+04     144  144
...                                     ...           ...     ...  ...
Zbigniew Zamachowski Comedy       1464625.0  1.464625e+06      92   92
Zooey Deschanel      Comedy      32391374.0  3.239137e+07      95   95
Çetin Tekindor       Drama      461855363.0  4.618554e+08     112  112
Éric Toledano        Biography   13182281.0  1.318228e+07     112  112
Ömer Faruk Sorak     Comedy     200178699.0  2.001787e+08     110  110

                                       Metascore
                                  mean       min   max  mean
Star1                Genre
Aamir Khan           Action     160.50       NaN   NaN   NaN
                     Adventure  224.00      84.0  84.0  84.0
                     Comedy     168.25      67.0  67.0  67.0
Aaron Taylor-Johnson Action     117.00      66.0  66.0  66.0
Abhay Deol           Drama      144.00       NaN   NaN   NaN
...                                ...       ...   ...   ...
Zbigniew Zamachowski Comedy      92.00      88.0  88.0  88.0
Zooey Deschanel      Comedy      95.00      76.0  76.0  76.0
Çetin Tekindor       Drama      112.00       NaN   NaN   NaN
Éric Toledano        Biography  112.00      57.0  57.0  57.0
Ömer Faruk Sorak     Comedy     110.00       NaN   NaN   NaN

[829 rows x 12 columns]

# Exercise

In [9]:
ipl= pd.read_csv(r"deliveries.csv")
ipl.head(20)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [42]:
# 1: find the top 10 batsman in terms of runs scored.
ipl.groupby("batsman")["batsman_runs"].sum().sort_values(ascending =False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [69]:
# 2: find the batsman with max no of sixes
sixes = ipl[ipl["batsman_runs"] == 6]
sixes.groupby("batsman")["batsman_runs"].count().sort_values(ascending = False).head(1).index[0]

'CH Gayle'

In [ ]:
# 3: find the batsman with most no of 4's and 6's in last 5 overs
filtered = ipl[(ipl["over"] > 15) & ((ipl["batsman_runs"]== 4) | (ipl["batsman_runs"] == 6))]
filtered.groupby("batsman")["batsman_runs"].value_counts().sort_values(ascending = False).head(2)

batsman   batsman_runs
MS Dhoni  4               187
          6               153
Name: count, dtype: int64

In [92]:
# 4: find V Kohli's record against all teams.
temp_df = ipl[ipl["batsman"]== "V Kohli"]
temp_df.groupby("bowling_team")["batsman_runs"].sum().sort_values(ascending=False).reset_index()

               bowling_team  batsman_runs
0          Delhi Daredevils           763
1       Chennai Super Kings           749
2     Kolkata Knight Riders           675
3           Kings XI Punjab           636
4            Mumbai Indians           628
5       Sunrisers Hyderabad           509
6          Rajasthan Royals           370
7           Deccan Chargers           306
8             Gujarat Lions           283
9   Rising Pune Supergiants           188
10            Pune Warriors           128
11   Rising Pune Supergiant            83
12           Delhi Capitals            66
13     Kochi Tuskers Kerala            50

In [ ]:
#5: find highest virat kohli score in ipl history
tem_df = ipl[ipl["batsman"] =="V Kohli"]
tem_df.groupby("match_id")["batsman_runs"].sum().sort_values(ascending =False).head(1).values[0]

np.int64(113)

In [110]:
# 6: create a function that can return the highest score of any batsman.
def highest(batsman):
    tem_df = ipl[ipl["batsman"] == batsman]
    return tem_df.groupby("match_id")["batsman_runs"].sum().sort_values(ascending =False).head(1).values[0]

highest("CH Gayle")

np.int64(175)