# **Pandas - 07 (B)**

## **Vectorized String Operations**

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# what are vectorized operations?
a = np.array([1,2,3,4])
a*4 # this operations is applied to all the elements of the array these type of operations are called vectorized operations.

array([ 4,  8, 12, 16])

In [ ]:
# problem in vectorized  operation in vanilla python
s = ["cat","hat",4,"rat"]
[i.startswith("c") for i in s] # this code will crack because int object has no attribute startswith this is the problem in vectorized operation in vanilla python.

AttributeError: 'int' object has no attribute 'startswith'

In [10]:
# how pandas solve this issue?
s = pd.Series(["cat","hat",4,"rat"])
# .str ---> string accessor ---> when we have to use the string type functions we always have to use this accesor
s.str.startswith("c") # it igonores the 4 and treat as NaN value for this operation
# it is fast and optimized.

0     True
1    False
2      NaN
3    False
dtype: object

In [24]:
# import titanic
titanic = pd.read_csv(r"C:\Hammad Mustafa\A Long Journey\Artificial Intelligence (AI)\Data Science (Machine Learning) Libraries\Pandas\Pandas - 07\titanic.csv")
titanic["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### **Common Functions**

In [ ]:
#lower
titanic["Name"].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [14]:
# upper()
titanic["Name"].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [15]:
# capitalize()
titanic["Name"].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [16]:
# title()
titanic["Name"].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [26]:
# len() --. count the no.  of characters of the a string in series.
titanic["Name"].str.len()
# fetch the name of the passenger whose name is larges from all.
index_of_largest_name =titanic["Name"].str.len().sort_values(ascending=False).head(1).index[0]
titanic["Name"][index_of_largest_name]

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'

In [36]:
# another method
large_name = titanic["Name"].str.len().max()
titanic[titanic["Name"].str.len() == large_name]["Name"].values[0]

'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'

In [ ]:
# strip ---> remove all the leading and trailing spaces of the string.
"           Hammad         ".strip()

'Hammad'

In [39]:
# in Pandas
titanic["Name"].str.strip() # ---> remove all unwanted spaces from the series

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
# split() -> split the string into parts on the basis of provided element.
titanic["Name"].str.split(" ") # split the Name column on the basis of "space".

0                           [Braund,, Mr., Owen, Harris]
1      [Cumings,, Mrs., John, Bradley, (Florence, Bri...
2                             [Heikkinen,, Miss., Laina]
3      [Futrelle,, Mrs., Jacques, Heath, (Lily, May, ...
4                          [Allen,, Mr., William, Henry]
                             ...
886                            [Montvila,, Rev., Juozas]
887                    [Graham,, Miss., Margaret, Edith]
888       [Johnston,, Miss., Catherine, Helen, "Carrie"]
889                           [Behr,, Mr., Karl, Howell]
890                              [Dooley,, Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [47]:
# get(index) --> get the nth index str element from the string after the split
titanic["Name"].str.split(" ").str.get(0)

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [25]:
# question:
# Add 3 more columns to the dataframe Named: First Name --> Sr.Name/last Name -->Title
titanic["last_name"] = titanic["Name"].str.split(",").str.get(0) # fetched the Sr.name/last Name of all the passangers
titanic["last_name"]

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: last_name, Length: 891, dtype: object

In [26]:
# n parameter ---> important # --> expand parameter make dataframe of columns in which splitting is performed
# again spliting
titanic[["title","first_name"]] = titanic["Name"].str.split(",").str.get(1).str.strip().str.split(" ",n=1,expand=True) # n=1 means only one split for the first space for the next spaces there is no split
titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina

In [77]:
# # Title
# # titanic["title"] = titanic["Name"].str.split(",").str.get(1).str.strip().str.split(" ",n=1).str.get(0)
# titanic.head(3)

In [78]:
# Questions 2: How many Mr. and Miss. are in titanic
titanic["title"].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Mlle.          2
Col.           2
Don.           1
Mme.           1
Ms.            1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [9]:
# replace() ---> replace a string with another provided value.
# q: replace the Ms.  & Mlle. (Miss) value with Miss. because they are same.
titanic["title"] = titanic["title"].str.replace("Ms.","Miss.")
titanic["title"] = titanic["title"].str.replace("Mlle.","Miss.")
titanic["title"].value_counts().sort_values(ascending=False)

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Mme.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

## **Filtering**

In [17]:
#startswith/endswith
titanic[titanic["Name"].str.startswith("A")] # all the passangers whose name starts with "A"

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,middle_name
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S,Andersson,Mr.,Anders Johan
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.00,1,5,347077,31.3875,NaN,S,Asplund,Mrs.,Carl Oscar (Selma Augusta Emilia Johansson)
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S,Ahlin,Mrs.,Johan (Johanna Persdotter Larsson)
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mrs.,Josef (Josefine Franchi)
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S,Andersson,Miss.,Erna Alexandra
91,92,0,3,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,347466,7.8542,NaN,S,Andreasson,Mr.,Paul Edvin
114,115,0,3,"Attalah, Miss. Malake",female,17.00,0,0,2627,14.4583,NaN,C,Attalah,Miss.,Malake
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Ellis Anna Maria
144,145,0,2,"Andrew, Mr. Edgardo Samuel",male,18.00,0,0,231945,11.5000,NaN,S,Andrew,Mr.,Edgardo Samuel
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.00,0,0,350043,7.7958,NaN,S,Andersson,Mr.,"August Edvard (""Wennerstrom"")"
182,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,NaN,S,Asplund,Master.,Clarence Gustaf Hugo
192,193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.00,1,0,350046,7.8542,NaN,S,Andersen-Jensen,Miss.,Carla Christine Nielsine
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.00,0,0,2699,18.7875,NaN,C,Albimona,Mr.,Nassef Cassem
210,211,0,3,"Ali, Mr. Ahmed",male,24.00,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Ali,Mr.,Ahmed
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S,Asplund,Miss.,Lillian Gertrud
244,245,0,3,"Attalah, Mr. Sleiman",male,30.00,0,0,2694,7.2250,NaN,C,Attalah,Mr.,Sleiman
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,Asplund,Master.,Edvin Rojj Felix
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S,Andrews,Miss.,Kornelia Theodosia
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.00,1,1,C.A. 2673,20.2500,NaN,S,Abbott,Mrs.,Stanton (Rosa Hunt)
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,Allison,Miss.,Helen Loraine
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,Allison,Master.,Hudson Trevor
308,309,0,2,"Abelson, Mr. Samuel",male,30.00,1,0,P/PP 3381,24.0000,NaN,C,Abelson,Mr.,Samuel
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.00,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mr.,Josef
363,364,0,3,"Asim, Mr. Adola",male,35.00,0,0,SOTON/O.Q. 3101310,7.0500,NaN,S,Asim,Mr.,Adola
365,366,0,3,"Adahl, Mr. Mauritz Nils Martin",male,30.00,0,0,C 7076,7.2500,NaN,S,Adahl,Mr.,Mauritz Nils Martin
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.00,0,0,PC 17477,69.3000,B35,C,Aubart,Mme.,Leontine Pauline
401,402,0,3,"Adams, Mr. John",male,26.00,0,0,341826,8.0500,NaN,S,Adams,Mr.,John
460,461,1,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S,Anderson,Mr.,Harry
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr.,Ramon
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,Allison,Mrs.,Hudson J C (Bessie Waldo Daniels)
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.00,1,0,226875,26.0000,NaN,S,Angle,Mrs.,"William A (Florence ""Mary"" Agnes Hughes)"
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Ingeborg Constanzia
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",female,11.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Sigrid Elisabeth
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S,Appleton,Mrs.,Edward Dale (Charlotte Lamson)
610,611,0,3,"Andersson, Mrs. Anders Johan (Alfrida Konstant...",female,39.00,1,5,347082,31.2750,NaN,S,Andersson,Mrs.,Anders Johan (Alfrida Konstantia Brogren)
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C,Astor,Mrs.,John Jacob (Madeleine Talmadge Force)
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,Allen,Miss.,Elisabeth Walton
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.00,1,1,C.A. 2673,20.2500,NaN,S,Abbott,Mr.,Rossmore Edward
780,781,1,3,"Ayoub, Miss. Banoura",female,13.00,0,0,2687,7.2292,NaN,C,Ayoub,Miss.,Banoura
784,785,0,3,"Ali, Mr. William",male,25.00,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,Ali,Mr.,William
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.00,0,0,112050,0.0000,A36,S,Andrews,Mr.,Thomas Jr
810,811,0,3,"Alexander, Mr. William",male,26.00,0,0,3474,7.8875,NaN,S,Alexander,Mr.,William
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Ebba Iris Alfrida
833,834,0,3,"Augustsson, Mr. Albert",male,23.00,0,0,347468,7.8542,NaN,S,Augustsson,Mr.,Albert
834,835,0,3,"Allum, Mr. Owen George",male,18.00,0,0,2223,8.3000,NaN,S,Allum,Mr.,Owen George
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.00,0,0,SOTON/O2 3101287,7.9250,NaN,S,Alhomaki,Mr.,Ilmari Rudolf
845,846,0,3,"Abbing, Mr. Anthony",male,42.00,0,0,C.A. 5547,7.5500,NaN,S,Abbing,Mr.,Anthony
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,Andersson,Master.,Sigvard Harald Elias
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.00,0,1,392091,9.3500,NaN,S,Aks,Mrs.,Sam (Leah Rosen)
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.00,1,0,P/PP 3381,24.0000,NaN,C,Abelson,Mrs.,Samuel (Hannah Wizosky)

In [27]:
# endswith()
titanic[titanic["Name"].str.endswith("A")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C,Stewart,Mr.,Albert A
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q,Keane,Miss.,Nora A

In [28]:
# isdigit/isaplha()
titanic[titanic["first_name"].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, last_name, title, first_name]
Index: []

### **Applying Regex (Regular Expressions)**

In [ ]:
# contains(case) --- > for searching specific part of the string 
#case parameter means case sensitivity True or False.
#  Q 1: search if the name of any passanger contains "john" or not.
titanic[titanic["first_name"].str.contains("john",case=False)]["Name"]

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
41     Turpin, Mrs. William John Robert (Dorothy Ann ...
45                              Rogers, Mr. William John
98                  Doling, Mrs. John T (Ada Julia Bone)
112                               Barton, Mr. David John
117                      Turpin, Mr. William John Robert
160                             Cribb, Mr. John Hatfield
162                           Bengtsson, Mr. John Viktor
165      Goldsmith, Master. Frank John William "Frankie"
168                                  Baumann, Mr. John D
188                                     Bourke, Mr. John
212                               Perkin, Mr. John Henry
226                            Mellors, Mr. William John
227                      Lovell, Mr. John Hall ("Henry")
324                             Sage, Mr. George John Jr
328       Goldsmith, Mrs. Frank John (Emily Alice Brown)
401                                      Adams, Mr. John
418                           Matthews, Mr. William John
467                           Smart, Mr. John Montgomery
527                                   Farthing, Mr. John
548                            Goldsmith, Mr. Frank John
549                       Davies, Master. John Morgan Jr
550                          Thayer, Mr. John Borland Jr
563                                    Simmons, Mr. John
572                     Flynn, Mr. John Irwin ("Irving")
574                         Rush, Mr. Alfred George John
581    Thayer, Mrs. John Borland (Marian Longstreth M...
583                                  Ross, Mr. John Hugo
586                              Jarvis, Mr. John Denzil
594                              Chapman, Mr. John Henry
613                                     Horgan, Mr. John
624                          Bowen, Mr. David John "Dai"
657                        Bourke, Mrs. John (Catherine)
694                                      Weir, Col. John
698                             Thayer, Mr. John Borland
700    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
733                           Berriman, Mr. William John
760                                   Garfirth, Mr. John
765                 Hogeboom, Mrs. John C (Anna Andrews)
818                     Holm, Mr. John Fredrik Alexander
822                      Reuchlin, Jonkheer. John George
825                                      Flynn, Mr. John
848                                    Harper, Rev. John
864                               Gill, Mr. John William
Name: Name, dtype: str

In [34]:
# Q 2: find last_name with start and end char vowel.
# in this question we have to write regular expression. (Must learn the Regex First)
titanic[titanic["last_name"].str.contains("^[aeiouAEIOU].+[aeiouAEIOU]$")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C,Uruchurtu,Don.,Manuel E
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mrs.,Josef (Josefine Franchi)
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,Albimona,Mr.,Nassef Cassem
210,211,0,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,NaN,S,Ali,Mr.,Ahmed
353,354,0,3,"Arnold-Franchi, Mr. Josef",male,25.0,1,0,349237,17.8000,NaN,S,Arnold-Franchi,Mr.,Josef
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr.,Ramon
518,519,1,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.0000,NaN,S,Angle,Mrs.,"William A (Florence ""Mary"" Agnes Hughes)"
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S,Ali,Mr.,William
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,Alhomaki,Mr.,Ilmari Rudolf

In [36]:
# Q 3: find last_name with start and end char consonant.
titanic[titanic["last_name"].str.contains("^[^aeiouAEIOU].+[^aeiouAEIOU]$")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,title,first_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Moran,Mr.,James
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,McCarthy,Mr.,Timothy J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,Sutehall,Mr.,Henry Jr
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss.,Margaret Edith
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston,Miss.,"Catherine Helen ""Carrie"""
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr.,Karl Howell
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr.,Patrick

In [38]:
# slicing
titanic["Name"].str[:4] # fetch 4 characters of every string object in series.
titanic["Name"].str[::2] # fetch alternate characters of every string in series.

0                    Ban,M.Oe ars
1      Cmns r.Jh rde Foec rgsTae)
2                     Hiknn is an
3          Ftel,Ms aqe et Ll a el
4                    Aln r ila er
                  ...
886                   Mnvl,Rv uzs
887                Gaa,Ms.Mrae dt
888          Jhso,Ms.CteieHln"are
889                   Bh,M.Kr oel
890                    Doe,M.Ptik
Name: Name, Length: 891, dtype: str

In [39]:
# Q: Reverse the Name of every passangers in the dataset
titanic["Name"].str[::-1]

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: str