## Multiindex Objects

In [2]:
import numpy as np
import pandas as pd

## Series is 1D & DataFrames are 2D Objects

### But Why?

### and what exactly is index?

## MultiIndex Series

In [2]:
# can we have multiple index? let's try
index_val =[("cse",2019),("cse",2020),("cse",2021),("cse",2022),("ece",2019),("ece",2020),("ece",2021),("ece",2022)] # list of tuples of indicies
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
# its working.
a[("cse",2021)]
a[("ece",2022)]

np.int64(8)

In [ ]:
# The problem:
a["cse"] 
# # i want to fetch all the rows in which cse data is stored but error because there is no index like "cse" it is combined ("cse",year) if we want to fetch data we have to provide all indicies in the tuple to fetch the result. this is the problem in this approach.

In [ ]:
# The solution ---> creating multiindex series -->uses multiindexing (also known as Hierarchical Indexing)
# multiple index levels within a single index

In [4]:
#how to create multiindex object?
# 1. pd.MultiIndex.from_tuples()
index_val =[("cse",2019),("cse",2020),("cse",2021),("cse",2022),("ece",2019),("ece",2020),("ece",2021),("ece",2022)] # list of tuples of indicies
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex # multiindex object

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [8]:
type(multiindex) # its type is Pandas.multiindex object

pandas.MultiIndex

In [7]:
# levels attribute
multiindex.levels # it decouples both the indicies given in a tuple and gives result in a frozen list

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [ ]:
multiindex.levels[0] # gives the 0th level of indexing --> branch

Index(['cse', 'ece'], dtype='str')

In [ ]:
multiindex.levels[1] # gives the 1st  level of indexing --> Year

Index([2019, 2020, 2021, 2022], dtype='int64')

In [9]:
# 2: by using pd.MultiIndex.from_product()
pd.MultiIndex.from_product([["cse","ece"],[2019,2020,2021,2022]]) # passing a 2d list
# it will do Cartesian Product between Set A (list 1) and Set B (list 2)

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [10]:
# creating a series with multiindex object
s = pd.Series([1,2,3,4,5,6,7,8],index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [11]:
# how to fetch items from such a series.
# fetching 4:
s[("cse",2022)]

np.int64(4)

In [ ]:
# fetch all the rows that have cse
s["cse"] # this we can access but in the above approach we cannot do this type of indexing
# we can access the branches of the tree.(Heirarchical Indexing)
s["ece"]

2019    5
2020    6
2021    7
2022    8
dtype: int64

In [ ]:
# a logical question to ask?
# what is its dimension?

# this series is 2d because for fetching any value we have to provide two pieces of information --> branch ---> year

In [ ]:
# then why we not use dataframe?
# actually we convert this 2d series into a dataframe.
# unstack() Function
temp =s.unstack() # converts multiIndex series (2d) into dataframe
temp   
# it converts the level_01 index  into columns and level_0 index remains the index of rows of the dataframe.
# we can fetch same data by giving two pieces of information.

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [ ]:
# stack() function ---> converts dataframe into MultiIndex series (2d)

temp.stack() # --> # it converts the columns into level_01 index and rows indexes become level_0 indexes for the series.

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [ ]:
# Then what was the point of multiindex series?
# basically we represent high dimension data (2d) using a lower dimension object Series (1d)
# we can represent any higher dimension data like 3d,4d...nd using lower dimension object Dataframe (2d)

## MultiIndex DataFrame

## MultiIndex Rows DataFrame

In [5]:
branch_df1 = pd.DataFrame([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
    [11,12],
    [13,14],
    [15,16]
],index = multiindex,columns= ["avg_package","students"])
branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [ ]:
# fetching items rows and columns
branch_df1.loc["cse"] # rows

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [22]:
branch_df1.loc["ece"]

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [ ]:
branch_df1["avg_package"] # return multiindex series

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [24]:
branch_df1["students"]

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

## MultiIndex Columns DataFrame

In [6]:
branch_df2 = pd.DataFrame([
    [1,2,0,0],
    [3,4,0,0],
    [56,0,0],
    [7,8,0,0]
],
index=[2019,2020,2021,2022],
columns= pd.MultiIndex.from_product([["Karachi","Lahore"],["avg_package","students"]])
)
branch_df2 # multiindex column dataframe hierrarchy is formed in the columns of the dataframe

# this is also a 3d data represented by using lower dimensional object dataframe (2d) but this is different from previous one because we are now doing multiIndexing on the basis of columns (Hierrarchy is formed in colums like ---> 1). City---> 2). (avg_package,students))

         Karachi               Lahore
     avg_package students avg_package students
2019           1        2           0      0.0
2020           3        4           0      0.0
2021          56        0           0      NaN
2022           7        8           0      0.0

In [31]:
# fetching data
branch_df2["Karachi"]

      avg_package  students
2019            1         2
2020            3         4
2021           56         0
2022            7         8

In [ ]:
branch_df2["Lahore"] # columns

      avg_package  students
2019            0       0.0
2020            0       0.0
2021            0       NaN
2022            0       0.0

In [ ]:
branch_df2["Karachi"]["students"] # column ---> columns

2019    2
2020    4
2021    0
2022    8
Name: students, dtype: int64

In [34]:
branch_df2["Lahore"]["avg_package"]

2019    0
2020    0
2021    0
2022    0
Name: avg_package, dtype: int64

In [ ]:
branch_df2.loc[2020] # rows ---> multiindex series as a result

Karachi  avg_package    3.0
         students       4.0
Lahore   avg_package    0.0
         students       0.0
Name: 2020, dtype: float64

In [37]:
branch_df2.loc[2022]

Karachi  avg_package    7.0
         students       8.0
Lahore   avg_package    0.0
         students       0.0
Name: 2022, dtype: float64

## MultiIndexing on Both Rows & Columns of the DataFrame

In [7]:
branch_df3 = pd.DataFrame([
    [1,2,0,0],
    [3,4,0,0],
    [5,6,0,0],
    [7,8,0,0],
    [9,10,0,0],
    [11,12,0,0],
    [13,14,0,0],
    [15,16,0,0]
],
    index = multiindex,
    columns=pd.MultiIndex.from_product([["Karachi","Lahore"],["avg_package","students"]])
)
branch_df3 # 4d data is represented using multiindex in 2d dataframe

             Karachi               Lahore
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## Stacking & Unstacking in Multindex Dataframes

In [46]:
temp_df =branch_df1.unstack() # level_01 indexes  becomes level_01 columns and existing columns become level_0 colums
temp_df

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16

In [50]:
temp_ser = temp_df.unstack() 
temp_ser# if we unstack again the level_0 index become level_02 column and no rows left only columsn so dataframe converted into series.

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [56]:
temp_df2 = temp_df.stack() # level_01 colum becomes level_01 indexes
temp_df2

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [58]:
temp_df2.stack() # level_0 column become level_02 index(row) and no cloumns left thats why dataframe becomes series.

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [60]:
branch_df2.unstack()

Karachi  avg_package  2019     1.0
                      2020     3.0
                      2021    56.0
                      2022     7.0
         students     2019     2.0
                      2020     4.0
                      2021     0.0
                      2022     8.0
Lahore   avg_package  2019     0.0
                      2020     0.0
                      2021     0.0
                      2022     0.0
         students     2019     0.0
                      2020     0.0
                      2021     NaN
                      2022     0.0
dtype: float64

In [63]:
branch_df2.stack().stack()

2019  avg_package  Karachi     1.0
                   Lahore      0.0
      students     Karachi     2.0
                   Lahore      0.0
2020  avg_package  Karachi     3.0
                   Lahore      0.0
      students     Karachi     4.0
                   Lahore      0.0
2021  avg_package  Karachi    56.0
                   Lahore      0.0
      students     Karachi     0.0
                   Lahore      NaN
2022  avg_package  Karachi     7.0
                   Lahore      0.0
      students     Karachi     8.0
                   Lahore      0.0
dtype: float64

In [ ]:
branch_df3.unstack().unstack() # --> 4d series

Karachi  avg_package  2019  cse     1
                            ece     9
                      2020  cse     3
                            ece    11
                      2021  cse     5
                            ece    13
                      2022  cse     7
                            ece    15
         students     2019  cse     2
                            ece    10
                      2020  cse     4
                            ece    12
                      2021  cse     6
                            ece    14
                      2022  cse     8
                            ece    16
Lahore   avg_package  2019  cse     0
                            ece     0
                      2020  cse     0
                            ece     0
                      2021  cse     0
                            ece     0
                      2022  cse     0
                            ece     0
         students     2019  cse     0
                            ece     0
                      2020  cse     0
                            ece     0
                      2021  cse     0
                            ece     0
                      2022  cse     0
                            ece     0
dtype: int64

In [67]:
branch_df3.stack().stack()

cse  2019  avg_package  Karachi     1
                        Lahore      0
           students     Karachi     2
                        Lahore      0
     2020  avg_package  Karachi     3
                        Lahore      0
           students     Karachi     4
                        Lahore      0
     2021  avg_package  Karachi     5
                        Lahore      0
           students     Karachi     6
                        Lahore      0
     2022  avg_package  Karachi     7
                        Lahore      0
           students     Karachi     8
                        Lahore      0
ece  2019  avg_package  Karachi     9
                        Lahore      0
           students     Karachi    10
                        Lahore      0
     2020  avg_package  Karachi    11
                        Lahore      0
           students     Karachi    12
                        Lahore      0
     2021  avg_package  Karachi    13
                        Lahore      0
           students     Karachi    14
                        Lahore      0
     2022  avg_package  Karachi    15
                        Lahore      0
           students     Karachi    16
                        Lahore      0
dtype: int64

## Working with MultiIndex DataFrames

In [9]:
#head and tail
branch_df3.head()

             Karachi               Lahore
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0

In [10]:
branch_df3.tail()

             Karachi               Lahore
         avg_package students avg_package students
cse 2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [11]:
# shape
branch_df3.shape

(8, 4)

In [ ]:
# info()
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Karachi, avg_package)  8 non-null      int64
 1   (Karachi, students)     8 non-null      int64
 2   (Lahore, avg_package)   8 non-null      int64
 3   (Lahore, students)      8 non-null      int64
dtypes: int64(4)
memory usage: 352.0+ bytes

In [ ]:
# duplicated()
branch_df3.duplicated()

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [17]:
# isnull()
branch_df3.isnull()

             Karachi               Lahore
         avg_package students avg_package students
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
ece 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

In [ ]:
# Extracting rows
# single
# fetch 3rd row
branch_df3.loc[('cse',2021)]

Karachi  avg_package    5
         students       6
Lahore   avg_package    0
         students       0
Name: (cse, 2021), dtype: int64

In [21]:
# multiple ---> using slicing
# fetch 1st,3rd,5th row
branch_df3.loc[("cse",2019):("ece",2020):2]

             Karachi               Lahore
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [ ]:
# using iloc ---> simole than loc
# fetch 1st row
branch_df3.iloc[0]

Karachi  avg_package    1
         students       2
Lahore   avg_package    0
         students       0
Name: (cse, 2019), dtype: int64

In [23]:
# fetch 1st ,3rd,5th rows
branch_df3.iloc[0:5:2]

             Karachi               Lahore
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [26]:
# Extracting cols
# single
branch_df3["Lahore"]["students"]

cse  2019    0
     2020    0
     2021    0
     2022    0
ece  2019    0
     2020    0
     2021    0
     2022    0
Name: students, dtype: int64

In [28]:
branch_df3

             Karachi               Lahore
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [ ]:
# multiple
# using iloc ---> simple providing indexes for both rows and cols
# fetch Karachi ->students & Lahore -> avg_package
branch_df3.iloc[:,1:3]

          Karachi      Lahore
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [ ]:
# Extracting both rows and columns
# fetch cse 2019 and ece 2019 row and select the columns Karachi -> students and Lahore ->avg_package
branch_df3.iloc[[0,4],[1,2]] # using fancy indexing for fetching rows and cols using iloc.

          Karachi      Lahore
         students avg_package
cse 2019        2           0
ece 2019       10           0

In [ ]:
# sort_index() --> sort both level_0 and level_1 index
branch_df3 # it is already sort in ascending order we will sort in descending order.
branch_df3.sort_index(ascending=False) # both indexes simultaneously order in descending order.

             Karachi               Lahore
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [ ]:
# different sorting on different indexes
# sort branch index descending order and year in ascending order
branch_df3.sort_index(ascending=[False,True])

             Karachi               Lahore
         avg_package students avg_package students
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0

In [38]:
# sorting only one index ---> level parameter
branch_df3.sort_index(level=1,ascending=False)
branch_df3.sort_index(level=0,ascending=False)

             Karachi               Lahore
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [ ]:
# transpose() ---> rows become columns and columns become rows (also applicable to normal DataFrame)
branch_df3.transpose()

                     cse                 ece
                    2019 2020 2021 2022 2019 2020 2021 2022
Karachi avg_package    1    3    5    7    9   11   13   15
        students       2    4    6    8   10   12   14   16
Lahore  avg_package    0    0    0    0    0    0    0    0
        students       0    0    0    0    0    0    0    0

In [ ]:
# swaplevel() -->  Swap the level of indexes. default axis=0 for rows
branch_df3.swaplevel() # swap the levels of indexes of rows

             Karachi               Lahore
         avg_package students avg_package students
2019 cse           1        2           0        0
2020 cse           3        4           0        0
2021 cse           5        6           0        0
2022 cse           7        8           0        0
2019 ece           9       10           0        0
2020 ece          11       12           0        0
2021 ece          13       14           0        0
2022 ece          15       16           0        0

In [ ]:
branch_df3.swaplevel(axis=1) # swap the levels of columns

         avg_package students avg_package students
             Karachi  Karachi      Lahore   Lahore
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## Wide Vs Long Data

**Wide Data Format**: Wide data format is where we have a single row for every data point with multiple columns to hold the values of various attributes.

**Long Data Format:** Long data format is where, for each data point we have as many rows as the number of attributes and each row contains the value of particular attribute for a given data point.

In [ ]:
# melt() convert wide data format into long data format
pd.DataFrame({
    "cse": [120]
}).melt()

  variable  value
0      cse    120

In [5]:
# var_name and value_name parameters
temp_df = pd.DataFrame({"cse":[120],"ese":[100],"mech":50})
temp_df # wide data

   cse  ese  mech
0  120  100    50

In [6]:
temp_df.melt(var_name="branch",value_name="num_students") # long data

  branch  num_students
0    cse           120
1    ese           100
2   mech            50

In [12]:
# id_vars --> parameter ---> makes a specific column --> id (like index) and does not make it row (means skip that specific column)
pd.DataFrame({
    "branch":["cse","ece","mech"],
    "2020": [100,150,60],
    "2021": [120,130,80],
    "2022": [150,140,70]
}).melt(id_vars= ["branch"],var_name="year",value_name="num_students")

  branch  year  num_students
0    cse  2020           100
1    ece  2020           150
2   mech  2020            60
3    cse  2021           120
4    ece  2021           130
5   mech  2021            80
6    cse  2022           150
7    ece  2022           140
8   mech  2022            70

In [28]:
death= pd.read_csv(r"C:\Hammad Mustafa\A Long Journey\Artificial Intelligence (AI)\Data Science (Machine Learning) Libraries\Pandas\Pandas - 06\time_series_covid19_deaths_global.csv")
confirm = pd.read_csv(r"C:\Hammad Mustafa\A Long Journey\Artificial Intelligence (AI)\Data Science (Machine Learning) Libraries\Pandas\Pandas - 06\time_series_covid19_confirmed_global.csv")

In [14]:
death.shape

(289, 1081)

In [29]:
# Make a Dataframe using death and confirm dataframes with columns --> Country -->Date --->Confirm ---> Deaths (convert wide data into long data)
death = death.melt(id_vars = ["Province/State","Country/Region","Lat","Long"],var_name = "Date",value_name = "num_deaths")
death

,Province/State,Country/Region,Lat,Long,Date,num_deaths
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [34]:
confirm = confirm.melt(id_vars=["Province/State","Country/Region","Lat","Long"],var_name="Date",value_name="num_cases")
confirm

,Province/State,Country/Region,Lat,Long,Date,num_cases
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981

In [37]:
corona_df= confirm.merge(death,on=["Province/State","Country/Region","Lat","Long","Date"],how="inner")[["Country/Region","Date","num_cases","num_deaths"]]
corona_df

              Country/Region     Date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]

In [ ]:
# pivot ---> converts long data format into wide data format