## **Plotly - 02**

# **15+ Plots in Plotly**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [2]:
# line chart
df = pd.read_csv(r"iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# sorting
df_sort = df.sort_values(by = "SepalWidthCm")
# plotting

fig = px.line(df_sort,x="SepalWidthCm",y="PetalWidthCm",color = "Species",width=1200,height=800)
fig.write_html("./Plots/Line Chart.html")

In [18]:
fig.show()

In [19]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# bar plot
# its necessary to group values based on means then plot
#
df_bar = df.groupby(["Species"]).mean().reset_index()
df_bar

,Species,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
0,Iris-setosa,25.5,5.006,3.418,1.464,0.244
1,Iris-versicolor,75.5,5.936,2.770,4.260,1.326
2,Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [30]:
fig = px.bar(df_bar,x="Species",y="SepalLengthCm",)
fig.show()

## BoxPlot

In [34]:
# boxplot
fig = px.box(df,x="Species",y="SepalLengthCm",color = "Species")
fig.show()

fig.write_html("./Plots/Boxplot in Plotly.html")

## **Violin Plot ---> Very Interactive**

In [37]:
# violon plot --> kde --> expension of the graph
fig = px.violin(df,x="Species",y="SepalWidthCm",color="Species")
fig.show()

In [40]:
# box plot in violin --> boz = True Parameter
fig = px.violin(df,x="Species",y="SepalWidthCm",color="Species",box = True)
fig.show()

fig.write_html("./Plots/Violin Plot in Plotly.html")

## **Histogram**

In [41]:
#histogram
vk = pd.read_csv(r"vk.csv")
vk.head()

   match_id  batsman_runs
0        12            62
1        17            28
2        20            64
3        27             0
4        30            10

In [52]:
# px.histogram()
# nbins parameter ---> no. of bins
fig = px.histogram(vk,x="batsman_runs", nbins=10,title="Virat Kohli IPL Career Analysis")
fig

## **Piechart**

In [59]:
# piechart
df_pie = df["Species"].value_counts().reset_index()
df_pie

           Species  count
0      Iris-setosa     50
1  Iris-versicolor     50
2   Iris-virginica     50

In [62]:
# px.pie(df,values,names)
fig = px.pie(df_pie,values="count",names="Species")
fig.show()

## **3D Scatter Plot**

In [5]:
# px.scatter_3d
fig = px.scatter_3d(df,x='SepalLengthCm',y='SepalWidthCm', z= 'PetalWidthCm', color = "Species")
fig.show()
fig.write_html("./Plots/ 3D Scatter Plot in plotly.html")

## **Area Chart**

In [7]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
# area chart

# px.area()
fig = px.area(df, x= "SepalWidthCm", y = "SepalLengthCm", color = "Species",title="Iris Analysis")
fig.show()
fig.write_html("./Plots/Area chart.html")

## **Bubble Chart**

#

In [19]:
# simple scatter but when size parameter is used
fig = px.scatter(df,x ="SepalLengthCm", y="SepalWidthCm", size="PetalWidthCm",title ="Bubble Chart")
fig.show()
fig.write_html("./Plots/Bubble Chart.html")

## **Sunburst Chart --> Best Interaction**

In [ ]:
# when primary categories has more categories then it is used
# path and values  parameter
df_sunburst = df.groupby(["Species","PetalWidthCm"]).size().reset_index(name="Counts") # creating subgroups in a group

fig = px.sunburst(df_sunburst, path=["Species","PetalWidthCm"], values = "Counts")
fig.show()

In [ ]:
# Practice -> Analysis of IPL Playoffs & Finals in Different Cities
ipl = pd.read_csv(r"ipl-matches.csv")
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [73]:
ipl = ipl[~(ipl["MatchNumber"].str.isdigit())]
host_match= ipl.groupby(["City","MatchNumber"])["MatchNumber"].count().reset_index(name="No. of Matches")
host_match.head()

        City        MatchNumber  No. of Matches
0  Abu Dhabi         Eliminator               1
1  Abu Dhabi        Qualifier 2               1
2  Ahmedabad              Final               1
3  Ahmedabad        Qualifier 2               1
4  Bangalore  Elimination Final               1

In [74]:
fig= px.sunburst(host_match,path=["City","MatchNumber"],values="No. of Matches",title="Analysis of IPL Playoffs & Finals in Different Cities")
fig.show()
fig.write_html("./Plots/Analysis of IPL Playoffs & Finals in Different Cities.html")

## **Paralllel Coordinates Plot**

In [16]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [26]:
# px.parallel_coordinates()
# removing id column and replacing Species categories with numbers for color parameter in function.
df_parallel = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm','Species']]

# another method of converting the category species in catcodes like 0,1,2 etc.

df_parallel["Species"] = df_parallel["Species"].astype("category").cat.codes
df_parallel.sample(5)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
50             7.0           3.2            4.7           1.4        1
17             5.1           3.5            1.4           0.3        0
22             4.6           3.6            1.0           0.2        0
60             5.0           2.0            3.5           1.0        1
107            7.3           2.9            6.3           1.8        2

In [24]:
# color, labels --> parameter
fig  = px.parallel_coordinates(df_parallel,color="Species",labels = {"Species":"Kinds"},width=1000,height=500)
fig.show()
fig.write_html("./Plots/Parallel Coordinates plot.html")

## **Density Contour Plots**

In [32]:
# px.density_contour()
fig = px.density_contour(df,x="SepalLengthCm", y="SepalWidthCm", color="Species")
fig.show()
fig.write_html("./Plots/Density Contour Plot.html")

## **Ternary plot**

In [6]:
# px.scatter_ternary() --> plot in Triangle --> a,b,c, color parameter
# use for finding outliers in the data
fig = px.scatter_ternary(df,a='SepalLengthCm',b='SepalWidthCm',c='PetalWidthCm', color="Species")
fig.show()
fig.write_html("./Plots/Scatter Ternary Plot.html")

## **Polar Chart (Radar Chart)**

In [ ]:
# px.line_polar ---> r, theta, line_close parameters
# usage:  give difference of different Categories on the basis of specific column
df_radar = df.groupby(["Species"]).mean().reset_index()
df_radar

,Species,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
0,Iris-setosa,25.5,5.006,3.418,1.464,0.244
1,Iris-versicolor,75.5,5.936,2.770,4.260,1.326
2,Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [12]:
fig = px.line_polar(df,r="PetalWidthCm",theta = "Species", line_close= True)
fig.show()
fig.write_html("./Plots/Polar (Radar) Chart.html")